print("ola usuario")
print("seja bem vindo")
print("qual seu nome?")
nome = input("nome: ")
print("qual sua senha?")
senha = input("senha:")
print("")
print("seu nome é: " + nome)
print("sua senha é: " + senha)
print("obrigado por usar nosso sistema")